blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('', views.post_list, name='post_list'),
	# path('<int:id>/', views.post_detail, name='post_detail'),
	path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
	path('<int:post_id>/share/', views.post_share, name='post_share'),
	path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
	path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag')
] 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager



class PublishedManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

	class Status(models.TextChoices):
		DRAFT = 'DF', 'Draft'
		PUBLISHED = 'PB', 'Published'

	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date='publish')
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

	objects = models.Manager()
	published = PublishedManager()

	tags = TaggableManager()

	class Meta:
		ordering = ['-publish']
		indexes = [
			models.Index(fields=['-publish'])
		]

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		# return reverse('blog:post_detail', args=[self.id])
		return reverse('blog:post_detail',
						args=[self.publish.year,
							  self.publish.month,
							  self.publish.day,
							  self.slug])



class Comment(models.Model):

	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
	name = models.CharField(max_length=80)
	email = models.EmailField()
	body = models.TextField()
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)


	class Meta:
		ordering = ['created']
		indexes = [
			models.Index(fields=['created']),
		]

	def __str__(self):
		return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):

	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
	class Meta:
		# создаем форму из модели
		model = Comment
		fields = ['name', 'email', 'body']
		#

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count



def post_list(request, tag_slug=None):
	post_list = Post.published.all()
	tag = None
	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		post_list = post_list.filter(tags__in=[tag])
	paginator = Paginator(post_list, 4)
	page_number = request.GET.get('page', 1)
	try:
		posts = paginator.page(page_number)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(paginator.num_pages)

	return render(request, 'blog/post/list.html', {'posts':posts, 'tag':tag})


# def post_detail(request, id): 
def post_detail(request, year, month, day, post):
	# post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
	post = get_object_or_404(Post, 
							status=Post.Status.PUBLISHED, 
							slug=post, 
							publish__year=year,
							publish__month=month,
							publish__day=day)

	comments = post.comments.filter(active=True)
	form = CommentForm()

	#список схожих постов
	post_tags_ids = post.tags.values_list('id', flat=True)
	similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

		
	return render(request, 'blog/post/detail.html', {'post':post, 'comments':comments, 'form':form, 'similar_posts': similar_posts})


def post_share(request, post_id):
	post = get_object_or_404(Post, id=post_id,
							 status=Post.Status.PUBLISHED)

	sent = False

	if request.method == 'POST':
		form = EmailPostForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = f"{cd['name']} recommends you read {post.title}"
			message = f"Read {post.title} at {post_url} \n\n" \
					f"{cd['name']}\'s comments: {cd['comments']}"
			send_mail(subject, message, cd['email'], [cd['to']])

			sent = True
	else:
		form = EmailPostForm()

	return render(request, 'blog/post/share.html', {'post':post, 'form':form, 'sent':sent})


@require_POST
def post_comment(request, post_id):
	post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)

	comment = None

	form = CommentForm(data=request.POST)

	if form.is_valid():
		comment = form.save(commit=False)
		comment.post = post
		comment.save()
	return render(request, 'blog/post/comment.html', {'post':post, 'form':form, 'comment':comment})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title %} {% endblock %}</title>
	<link href="{% static "css/blog.css"%}" rel="stylesheet">
</head>	
<body>
	<div id='content'>
		{% block content %}
		{% endblock %}
	</div>
	<div id='sidebar'>
		<h2><a href="{% url 'blog:post_list' %}">My blog</a></h2>
		<p>
			This is my blog.<br>
			I've written {% total_posts %} posts.	
		</p>
		<h3>Latest posts</h3>
		{% show_latest_posts 4 %}

		<h3>Most commented posts</h3>
		{% show_more_comments_posts 4 %}
	</div>
</body>
</html>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}


{% block title %} Add a comment {% endblock %}

{% block content %}
	{% if comment %}
		<h2> Your comment has been added.</h2>
		<p>
			<a href="{{ post.get_absolute_url }}">Back to the post</a>
		</p>
	{% else %}
	{% include 'blog/post/includes/comment_form.html' %}
	{% endif %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{post.title}}{% endblock %}

{% block content %}
	<h1>{{post.title}}</h1>
	<p class="date">
		Publiched {{post.publish}} by {{post.author}}
	</p>
	{{post.body|markdown}}
	<p>
		<a href="{% url "blog:post_share" post.id %}">Share this post</a>
	</p>
	<h2>Similar posts</h2>
	{% for post in similar_posts %}
		<p>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</p>
	{% empty %}
		There are no similar posts yet.
	{% endfor %}

	{% with comments.count as total_comments %}
		<h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
	{% endwith %}

	{% for comment in comments %}
		<div class="comment">
			<p class="info">
				Comment {{forloop.counter}} by {{comment.name}}
				{{comment.created}}
			</p>
			{{comment.body|linebreaks}}
		</div>
	{% empty %}
		There are no comments
	{% endfor %}
	{% include 'blog/post/includes/comment_form.html' %}
{% endblock %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form method="post" action="{% url 'blog:post_comment' post.id %}">
	{{form.as_div}}
	{% csrf_token %}
	<p><input type="submit" value="Add comment"></p>
</form>

blog/templates/blog/post/latest_posts.html
<ul>
	{% for post in latest_posts %}
		<li>
			<a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
		</li>
	{% endfor %}
</ul

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog {% endblock %}

{% block content %}
	<h1>My blog</h1>
	{% if tag %}
		<h2>Posts tagged with "{{ tag.name }}"</h2>
	{% endif %}
	{% for post in posts %}
		<h2>
			<a href="{{ post.get_absolute_url }}">
				{{post.title}}
			</a>
		</h2>
		<p class="tags">
			{% if post.tags.all %}
				Tags:
				{% for tag in post.tags.all %}
					
					<a href="{% url 'blog:post_list_by_tag' tag.slug %}">
						{{tag.name}}
					</a>
				{% if not forloop.last %}, {% endif %}
				{% endfor %}
			{% endif %}
		</p>
		<p class="date">
			Published {{post.publish}} by {{post.author}}
		</p>
		{# {{post.body|truncatewords:30|linebreaks}} #}
		{{post.body|markdown|truncatewords_html:30}}
		<hr>
	{% empty %}
		<p>No posts</p>
	{% endfor %}
	{% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/more_comments_posts.html
<ul>
	{% for post in more_comments_posts %}
		<li>
			<a href="{{post.get_absolute_url}}">{{ post.title }}</a>
		</li>
	{% endfor %}
</ul>

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}

{% block content %}
	{% if sent %}
		<h1>Email succesfully sent</h1>
		<p>
			"{{post.title}}" was successfully sent to {{form.cleaned_data.to}}
		</p>
	{%else%}
		<h1>Share "{{post.title}}" by email</h1>
		<form method="post">
			{{form.as_p}}
			{% csrf_token%}
			<input type="submit" value="Send email">
		</form>
	{%endif%}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{page.previous_page_number}}">Previous</a>
		{% endif%}
		<span class="current">
			Page {{page.number}} of {{page.paginator.num_pages}}.
		</span>
		{% if page.has_next %}
			<a href="?page={{page.next_page_number}}">Next</a>
		{% endif %}
	</span>
</div>

templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{page.previous_page_number}}">Previous</a>
		{% endif%}
		<span class="current">
			Page {{page.number}} of {{page.paginator.num_pages}}.
		</span>
		{% if page.has_next %}
			<a href="?page={{page.next_page_number}}">Next</a>
		{% endif %}
	</span>
</div>